version: '3'
services:
  mongodb:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
  browserless-crome:
    image: browserless/chrome:latest
    environment:
      - DEBUG=browserless:*
      - MAX_CONCURRENT_SESSIONS=10
      - CONNECTION_TIMEOUT=60000
      - MAX_QUEUE_LENGTH=20
      - PREBOOT_CHROME=true
      - DEMO_MODE=false
      - HOST=0.0.0.0
      - ENABLE_DEBUGGER=false
      - TOKEN=${BROWSERLESS_TOKEN}
      - PORT=3083
      - WORKSPACE_DELETE_EXPIRED=true
    container_name: "browserless-crome"
    restart: always
    ports:
      - "3083:3083"
    volumes:
      - "/var/docker-compose/parser/data:/data"
      - "/var/docker-compose/parser/home:~"
